# fly.toml app configuration file generated for jobpilot-little-valley-4408 on 2026-08-16T18:26:44+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobpilot-little-valley-4408'
primary_region = 'sjc'

[build]
  builder = 'heroku'

[env]
  GEMINI_MODEL = 'gemini-3-flash-preview'
  PORT = '8080'

[[mounts]]
  source = 'jobpilot_data'
  destination = '/app/data'
  processes = ['app']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  ports = []
  processes = ['app']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'

[checks]
  [checks.http]
    type = 'http'
    interval = '10s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
